apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpacking
  labels:
    app: productpacking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpacking
  template:
    metadata:
      labels:
        app: productpacking
    spec:
      containers:
        - name: productpacking
          image: username/productpacking:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5